const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Behaviors.Pin,
		C3.Plugins.NinePatch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.LoadState
	];
};
self.C3_JsPropNameTable = [
	{ShieldAbility: 0},
	{HealAbility: 0},
	{Sine: 0},
	{Tween: 0},
	{EnemySprite: 0},
	{DragDrop: 0},
	{Card1: 0},
	{Card2: 0},
	{Card3: 0},
	{Card4: 0},
	{SkillTitle1A: 0},
	{SkillDesc1: 0},
	{SkillCost1: 0},
	{SkillTitle2A: 0},
	{SkillDesc2: 0},
	{SkillCost2Outline: 0},
	{Hit: 0},
	{Defend: 0},
	{HP: 0},
	{MP: 0},
	{EnemyHP: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{CarbName: 0},
	{EnemyNameMaine: 0},
	{HoldLabel: 0},
	{HitLabel: 0},
	{Sprite4: 0},
	{BG_DG: 0},
	{EnemyBG_DG: 0},
	{FinalHits: 0},
	{Timer: 0},
	{DG: 0},
	{EnemyDG: 0},
	{Touch: 0},
	{BGHitRoll: 0},
	{HitRoll: 0},
	{BGHitRoll2: 0},
	{AJAX: 0},
	{Array_Skills: 0},
	{Array_Order: 0},
	{Array_SkillsFinal: 0},
	{SkillPlay: 0},
	{SkillDiscard: 0},
	{bgtest: 0},
	{Sprite5: 0},
	{EnemyNameOutline: 0},
	{CarbNameOutline: 0},
	{CarbNameMain: 0},
	{SkillTitle1B: 0},
	{SkillTitle2B: 0},
	{Aegis1: 0},
	{Aegis2: 0},
	{Aegis3: 0},
	{IconResurrection: 0},
	{Sprite7: 0},
	{SkillCost1Outline: 0},
	{SkillCost2: 0},
	{Food1: 0},
	{Food2: 0},
	{Food3: 0},
	{Food4: 0},
	{Food5: 0},
	{Food6: 0},
	{Pin: 0},
	{Body: 0},
	{InTouch: 0},
	{OK2Express: 0},
	{Head: 0},
	{Tail: 0},
	{LeftEar: 0},
	{RightEar: 0},
	{Mark: 0},
	{Expression: 0},
	{Sprite14: 0},
	{Stat: 0},
	{Code: 0},
	{CodeInput: 0},
	{Sprite6: 0},
	{CodeUp: 0},
	{CodeDown: 0},
	{Hat: 0},
	{RandomButton: 0},
	{Randomize: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{ButtonVenture: 0},
	{ButtonAchieve: 0},
	{ButtonShop: 0},
	{ButtonCloset: 0},
	{ButtonFood: 0},
	{BreedReady: 0},
	{ButtonEvolve: 0},
	{ButtonSettings: 0},
	{ButtonWeb: 0},
	{ButtonBluesky: 0},
	{Heart1: 0},
	{Heart2: 0},
	{Heart3: 0},
	{Sprite10: 0},
	{Purchase: 0},
	{GilIcon: 0},
	{Money: 0},
	{Text2: 0},
	{Sprite13: 0},
	{Sprite15: 0},
	{Purchased: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{"9patch": 0},
	{MENU_Venture: 0},
	{Text: 0},
	{GoVenture: 0},
	{Aegis4: 0},
	{EnemySprite2: 0},
	{EventPopup: 0},
	{ENEMYATTACK: 0},
	{Aegis5: 0},
	{"9patch2": 0},
	{PromptHeadBack: 0},
	{PressOn: 0},
	{HeadBack: 0},
	{VictoryMessage: 0},
	{"9patch3": 0},
	{Sprite: 0},
	{"9patch4": 0},
	{ButtonEvolve2: 0},
	{"9patch5": 0},
	{CrystalShards: 0},
	{purchased1: 0},
	{purchased2: 0},
	{Closet1: 0},
	{Closet2: 0},
	{Closet3: 0},
	{Closet4: 0},
	{Closet5: 0},
	{Closet6: 0},
	{Page: 0},
	{Page2: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{PassBG: 0},
	{PASS1: 0},
	{PASS2: 0},
	{PASS3: 0},
	{PASS4: 0},
	{Sprite20: 0},
	{CODENUM: 0},
	{Down: 0},
	{Up: 0},
	{EX: 0},
	{SECRET: 0},
	{Sprite21: 0},
	{Bred: 0},
	{Back: 0},
	{breed: 0},
	{friendbreed: 0},
	{CHOOSEBUTTON: 0},
	{REROLL: 0},
	{"9patch6": 0},
	{"9patch7": 0},
	{BREEEEED: 0},
	{Browser: 0},
	{STARTRANDOM: 0},
	{STARTSTANDARD: 0},
	{Sprite23: 0},
	{Text3: 0},
	{DGBuffer: 0},
	{EnemyDGBuffer: 0},
	{Turn: 0},
	{EnemyAggresion: 0},
	{Winner: 0},
	{HitAmount: 0},
	{Deck: 0},
	{Radiant: 0},
	{TempDamage: 0},
	{Resurrect: 0},
	{Transformed: 0},
	{Newcardtemp: 0},
	{Test: 0},
	{TempDG: 0},
	{EnemyName1: 0},
	{EnemyName2: 0},
	{EnemyPresent: 0},
	{EnemyMP: 0},
	{Hello: 0},
	{DNA: 0},
	{DNA_Body: 0},
	{DNA_Ear: 0},
	{DNA_Tail: 0},
	{DNA_Color1: 0},
	{DNA_Color2: 0},
	{DNA_Sat: 0},
	{DNA_Bright: 0},
	{DNA_Taste: 0},
	{DNA_Body2: 0},
	{DNA_Ear2: 0},
	{DNA_Tail2: 0},
	{DNA_Color3: 0},
	{DNA_Color4: 0},
	{DNA_Sat2: 0},
	{DNA_Bright2: 0},
	{DNA_Taste2: 0},
	{Affection: 0},
	{Food: 0},
	{MenuStatus: 0},
	{Eating: 0},
	{Gil: 0},
	{FoodType: 0},
	{Shards: 0},
	{closetpage: 0},
	{PurchasedGlasses: 0},
	{PurchasedArchon: 0},
	{PurchasedMiqo: 0},
	{PurchasedValor: 0},
	{PurchasedWisdom: 0},
	{PurchasedRyne: 0},
	{PurchasedNutkin: 0},
	{PurchasedCrystal: 0},
	{PurchasedFake: 0},
	{PurchasedTalia: 0},
	{PurchasedMhar: 0},
	{CODE1: 0},
	{CODE2: 0},
	{CODE3: 0},
	{CODE4: 0},
	{ACTIVEHAT: 0},
	{BloodMoney: 0},
	{KO: 0},
	{dialogue: 0},
	{tutorial: 0}
];

self.InstanceType = {
	EnemySprite: class extends self.ISpriteInstance {},
	Card1: class extends self.ISpriteInstance {},
	Card2: class extends self.ISpriteInstance {},
	Card3: class extends self.ISpriteInstance {},
	Card4: class extends self.ISpriteInstance {},
	SkillTitle1A: class extends self.ITextInstance {},
	SkillDesc1: class extends self.ITextInstance {},
	SkillCost1: class extends self.ITextInstance {},
	SkillTitle2A: class extends self.ITextInstance {},
	SkillDesc2: class extends self.ITextInstance {},
	SkillCost2Outline: class extends self.ITextInstance {},
	Hit: class extends self.ISpriteInstance {},
	Defend: class extends self.ISpriteInstance {},
	HP: class extends self.ISpriteInstance {},
	MP: class extends self.ISpriteInstance {},
	EnemyHP: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	CarbName: class extends self.ITextInstance {},
	EnemyNameMaine: class extends self.ITextInstance {},
	HoldLabel: class extends self.ITextInstance {},
	HitLabel: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	BG_DG: class extends self.ISpriteInstance {},
	EnemyBG_DG: class extends self.ISpriteInstance {},
	DG: class extends self.ISpriteInstance {},
	EnemyDG: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	BGHitRoll: class extends self.ISpriteInstance {},
	HitRoll: class extends self.ITextInstance {},
	BGHitRoll2: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Array_Skills: class extends self.IArrayInstance {},
	Array_Order: class extends self.IArrayInstance {},
	Array_SkillsFinal: class extends self.IArrayInstance {},
	SkillPlay: class extends self.ISpriteInstance {},
	SkillDiscard: class extends self.ISpriteInstance {},
	bgtest: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	EnemyNameOutline: class extends self.ITextInstance {},
	CarbNameOutline: class extends self.ITextInstance {},
	CarbNameMain: class extends self.ITextInstance {},
	SkillTitle1B: class extends self.ITextInstance {},
	SkillTitle2B: class extends self.ITextInstance {},
	Aegis1: class extends self.ISpriteInstance {},
	Aegis2: class extends self.ISpriteInstance {},
	Aegis3: class extends self.ISpriteInstance {},
	IconResurrection: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	SkillCost1Outline: class extends self.ITextInstance {},
	SkillCost2: class extends self.ITextInstance {},
	Body: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	Tail: class extends self.ISpriteInstance {},
	LeftEar: class extends self.ISpriteInstance {},
	RightEar: class extends self.ISpriteInstance {},
	Mark: class extends self.ISpriteInstance {},
	Expression: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	CodeInput: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	CodeUp: class extends self.ISpriteInstance {},
	CodeDown: class extends self.ISpriteInstance {},
	Hat: class extends self.ISpriteInstance {},
	RandomButton: class extends self.ISpriteInstance {},
	Randomize: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	ButtonVenture: class extends self.ISpriteInstance {},
	ButtonAchieve: class extends self.ISpriteInstance {},
	ButtonShop: class extends self.ISpriteInstance {},
	ButtonCloset: class extends self.ISpriteInstance {},
	ButtonFood: class extends self.ISpriteInstance {},
	ButtonEvolve: class extends self.ISpriteInstance {},
	ButtonSettings: class extends self.ISpriteInstance {},
	ButtonWeb: class extends self.ISpriteInstance {},
	ButtonBluesky: class extends self.ISpriteInstance {},
	Heart1: class extends self.ISpriteInstance {},
	Heart2: class extends self.ISpriteInstance {},
	Heart3: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Purchase: class extends self.ISpriteInstance {},
	GilIcon: class extends self.ISpriteInstance {},
	Money: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Food1: class extends self.ISpriteInstance {},
	Food2: class extends self.ISpriteInstance {},
	Food3: class extends self.ISpriteInstance {},
	Food4: class extends self.ISpriteInstance {},
	Food5: class extends self.ISpriteInstance {},
	Food6: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	_9patch: class extends self.I9PatchInstance {},
	MENU_Venture: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	GoVenture: class extends self.ISpriteInstance {},
	Aegis4: class extends self.ISpriteInstance {},
	EnemySprite2: class extends self.ISpriteInstance {},
	EventPopup: class extends self.ISpriteInstance {},
	ENEMYATTACK: class extends self.ITextInstance {},
	Aegis5: class extends self.ISpriteInstance {},
	_9patch2: class extends self.I9PatchInstance {},
	PromptHeadBack: class extends self.ISpriteInstance {},
	PressOn: class extends self.ISpriteInstance {},
	HeadBack: class extends self.ISpriteInstance {},
	VictoryMessage: class extends self.ISpriteInstance {},
	_9patch3: class extends self.I9PatchInstance {},
	Sprite: class extends self.ISpriteInstance {},
	_9patch4: class extends self.I9PatchInstance {},
	ButtonEvolve2: class extends self.ISpriteInstance {},
	_9patch5: class extends self.I9PatchInstance {},
	CrystalShards: class extends self.ISpriteInstance {},
	Closet1: class extends self.ISpriteInstance {},
	Closet2: class extends self.ISpriteInstance {},
	Closet3: class extends self.ISpriteInstance {},
	Closet4: class extends self.ISpriteInstance {},
	Closet5: class extends self.ISpriteInstance {},
	Closet6: class extends self.ISpriteInstance {},
	Page: class extends self.ISpriteInstance {},
	Page2: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	PassBG: class extends self.ISpriteInstance {},
	PASS1: class extends self.ITextInstance {},
	PASS2: class extends self.ITextInstance {},
	PASS3: class extends self.ITextInstance {},
	PASS4: class extends self.ITextInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Down: class extends self.ISpriteInstance {},
	Up: class extends self.ISpriteInstance {},
	EX: class extends self.ITextInstance {},
	SECRET: class extends self.ITextInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Back: class extends self.ISpriteInstance {},
	breed: class extends self.ISpriteInstance {},
	friendbreed: class extends self.ISpriteInstance {},
	CHOOSEBUTTON: class extends self.ISpriteInstance {},
	REROLL: class extends self.ISpriteInstance {},
	_9patch6: class extends self.I9PatchInstance {},
	_9patch7: class extends self.I9PatchInstance {},
	BREEEEED: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	STARTRANDOM: class extends self.ISpriteInstance {},
	STARTSTANDARD: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {}
}